const AUTH_CODES = {
  EMAIL_ALREADY_REGISTERED: "EMAIL_ALREADY_REGISTERED",

  MOBILE_ALREADY_REGISTERED: "MOBILE_ALREADY_REGISTERED",

  NAME_ALREADY_IN_USE: "NAME_ALREADY_IN_USE",

  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",

  ACTIVE_SESSION_EXISTS: "ACTIVE_SESSION_EXISTS",

  SESSION_EXPIRED: "SESSION_EXPIRED",

  ACCOUNT_INACTIVE: "ACCOUNT_INACTIVE",

  // Contact verification (OTP)
  CONTACT_VERIFICATION_REQUIRED: "CONTACT_VERIFICATION_REQUIRED",
  VERIFICATION_SESSION_EXPIRED: "VERIFICATION_SESSION_EXPIRED",
  ALREADY_VERIFIED: "ALREADY_VERIFIED",
  OTP_INVALID_CHANNEL: "OTP_INVALID_CHANNEL",
  OTP_INVALID: "OTP_INVALID",
  OTP_EXPIRED: "OTP_EXPIRED",
  OTP_NOT_FOUND: "OTP_NOT_FOUND",
  OTP_TOO_MANY_ATTEMPTS: "OTP_TOO_MANY_ATTEMPTS",
  OTP_RESEND_COOLDOWN: "OTP_RESEND_COOLDOWN",
  OTP_RATE_LIMITED: "OTP_RATE_LIMITED",

  // Google sign-in
  GOOGLE_NOT_CONFIGURED: "GOOGLE_NOT_CONFIGURED",
  GOOGLE_AUTH_FAILED: "GOOGLE_AUTH_FAILED",
  OAUTH_INVALID_STATE: "OAUTH_INVALID_STATE",
  OAUTH_INVALID_REDIRECT: "OAUTH_INVALID_REDIRECT",
  OAUTH_INVALID_ROLE: "OAUTH_INVALID_ROLE",
};

module.exports = AUTH_CODES;
